# Generated by Django 3.2.8 on 2021-10-13 14:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211012_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negocio',
            name='fk',
        ),
        migrations.AddField(
            model_name='negocio',
            name='fk_id',
            field=models.ForeignKey(db_column='fk_id', default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to='core.categ'),
            preserve_default=False,
        ),
    ]
