# Generated by Django 3.2.8 on 2021-10-13 15:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211013_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negocio',
            name='fk_id',
        ),
        migrations.AddField(
            model_name='negocio',
            name='fk',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='core.categ'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='categ',
            table=None,
        ),
        migrations.AlterModelTable(
            name='negocio',
            table=None,
        ),
    ]
