# Generated by Django 3.2.8 on 2021-10-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211013_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categ',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
